# Generated by Django 4.2.11 on 2024-05-08 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.CharField(max_length=300)),
                ("created", models.DateTimeField()),
                ("read", models.BooleanField(default=False)),
                ("tag", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Warning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=20)),
                ("content", models.CharField(max_length=300)),
                ("warningTime", models.CharField(max_length=30)),
                ("created", models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.CharField(default="static/default.png", max_length=200),
        ),
        migrations.AddField(
            model_name="user",
            name="cities",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.CharField(max_length=1000)),
                ("reply", models.CharField(max_length=1000)),
                ("status", models.CharField(default="未处理", max_length=40)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.user"
                    ),
                ),
            ],
        ),
    ]
