# Generated by Django 4.2.11 on 2024-05-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_notice_warning_user_avatar_user_cities_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="reply",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
