# Generated by Django 5.0.6 on 2024-05-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_feedback_reply_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=50)),
                ('sendType', models.CharField(choices=[('register', '注册'), ('forget', '忘记密码')], default='register', max_length=50)),
                ('sendTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='notice',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cities',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='warning',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
