# Generated by Django 4.2 on 2024-05-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_emailverify_sendtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='123@buaa.edu.cn', max_length=40),
            preserve_default=False,
        ),
    ]
